import Doctor from "./models/doctor"

export function getMockDoctors(): Doctor[] {
  return [
    {
      id: "1",
      name: "Dr. Rajesh Kumar",
      specialty: "General Physician",
      experience: 15,
      location: "Delhi",
      hospital: "Apollo Hospital, Delhi",
      education: ["MBBS", "MD - General Medicine"],
      languages: ["English", "Hindi"],
      fees: 800,
      rating: 4.8,
      reviewCount: 245,
      availability: {
        today: true,
        tomorrow: true,
        slots: ["10:00 AM", "12:30 PM", "4:00 PM", "6:30 PM"],
      },
      image: "/confident-male-doctor.png",
      gender: "male",
    },
    {
      id: "2",
      name: "Dr. Priya Sharma",
      specialty: "General Physician",
      experience: 12,
      location: "Mumbai",
      hospital: "Apollo Hospital, Mumbai",
      education: ["MBBS", "DNB - Family Medicine"],
      languages: ["English", "Hindi", "Marathi"],
      fees: 1000,
      rating: 4.7,
      reviewCount: 189,
      availability: {
        today: false,
        tomorrow: true,
        slots: ["11:00 AM", "3:00 PM", "5:30 PM"],
      },
      image: "/confident-female-doctor.png",
      gender: "female",
    },
    {
      id: "3",
      name: "Dr. Suresh Patel",
      specialty: "General Physician",
      experience: 20,
      location: "Bangalore",
      hospital: "Apollo Hospital, Bangalore",
      education: ["MBBS", "MD - Internal Medicine", "DM - Cardiology"],
      languages: ["English", "Hindi", "Kannada"],
      fees: 1200,
      rating: 4.9,
      reviewCount: 312,
      availability: {
        today: true,
        tomorrow: true,
        slots: ["9:00 AM", "1:00 PM", "7:00 PM"],
      },
      image: "/confident-male-doctor.png",
      gender: "male",
    },
    {
      id: "4",
      name: "Dr. Ananya Reddy",
      specialty: "General Physician",
      experience: 8,
      location: "Hyderabad",
      hospital: "Apollo Hospital, Hyderabad",
      education: ["MBBS", "MD - General Medicine"],
      languages: ["English", "Hindi", "Telugu"],
      fees: 700,
      rating: 4.5,
      reviewCount: 156,
      availability: {
        today: true,
        tomorrow: false,
        slots: ["10:30 AM", "2:30 PM", "6:00 PM"],
      },
      image: "/confident-female-doctor.png",
      gender: "female",
    },
    {
      id: "5",
      name: "Dr. Vikram Singh",
      specialty: "General Physician",
      experience: 18,
      location: "Chennai",
      hospital: "Apollo Hospital, Chennai",
      education: ["MBBS", "MD - Internal Medicine"],
      languages: ["English", "Hindi", "Tamil"],
      fees: 900,
      rating: 4.6,
      reviewCount: 210,
      availability: {
        today: false,
        tomorrow: true,
        slots: ["11:30 AM", "3:30 PM", "7:30 PM"],
      },
      image: "/confident-male-doctor.png",
      gender: "male",
    },
  ]
}
